### ISSUE TITLE
Request options: --path, --dry, --list and count match files

### ISSUE THREAD

**Issue by qaharmdz** [visavi/cleanup#1]
Please add few more options:

`-p, --path` to find on specific path
`-d, --dry` to run without actual remove
`-l, --list` to list the filename or print `.` dot on screen to represent single file(s) or dir(s)

and optionally show counted match files would be great.

Thank for the simple yet very usefull app.

**Comment by visavi** [comment]
will be done soon
only I did not understand why the --list parameter
what should it display?

**Comment by qaharmdz** [comment]
When I use cleanup, it show thousands deleted file quite fast; which is also good because it's indicate that the app is working and removed.

To have similiar progressing effect, just like on PHPUnit output; instead of show list of deleted file, change it to `.` dot. One dot represent one file which is the default options, and the `--list` parameter will show the deleted filename is like how it's working now.

If you like current deleted file to show as default, than please add another parameter that will change deleted filename into dot.

Thanks and I hope it's clear now.

**Comment by qaharmdz** [comment]
The output may looks like this:

```
Cleanup v1.5.0
................................................................................................
................................................................................................
................................................................................................
..................................................................
1021 file(s) successfuly removed.
```

**Comment by visavi** [comment]
Complited https://github.com/visavi/cleanup/releases/tag/v1.5.0
the default points are shown as in phpunit
to show more information you need to specify the parameter --verbose(-v)

**Comment by qaharmdz** [comment]
Awesome, thank you!
